version: '3.8'

services:
  backend:
    build:
      context: ./backend_server
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./react_project
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend

